better logging, messages, format

diff --git a/simbamon/simbamond b/simbamon/simbamond
--- a/simbamon/simbamond
+++ b/simbamon/simbamond
@@ -53,9 +53,6 @@ do_start()
   start-stop-daemon --start --pidfile $PIDFILE --exec ${DAEMON} \
     -- $DAEMON_ARGS \
     || return 2
-  # Add code here, if necessary, that waits for the process to be ready
-  # to handle requests from services started subsequently which depend
-  # on this one.  As a last resort, sleep for some time.
 
   log_success_msg $NAME started
 }
@@ -63,16 +60,16 @@ do_start()
 # Function that stops the daemon/service
 do_stop()
 {
-  # hmmm... can't get start-stop-daemon to kill the bugger...
+  # Hmmm... can't get start-stop-daemon to kill the bugger...
   PID=`cat $PIDFILE`
   kill ${PID}
   RETVAL="$?"
-  ps ax |grep -s ${PID} && \
+  ps ax |grep -q ${PID} && \
     log_success_msg ${NAME} stopped && return "$RETVAL"
   sleep 2
   kill -9 ${PID}
   RETVAL="$?"
-  ps ax |grep -s ${PID} && \
+  ps ax |grep -q ${PID} && \
     log_success_msg ${NAME} stopped && return "$RETVAL"
   # TODO killall $DAEMON
   log_success_msg failed to kill ${NAME}, trying default method...
@@ -112,62 +109,59 @@ do_reload() {
   return 0
 }
 
+# Do the work
 case "$1" in
   start)
-  [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-  do_start
-  case "$?" in
-    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-  esac
-  ;;
+    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+    do_start
+    case "$?" in
+      0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+      2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
+    ;;
   stop)
-  [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-  do_stop
-  case "$?" in
-    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-  esac
-  ;;
+    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+    do_stop
+    case "$?" in
+      0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+      2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
+    ;;
   status)
-       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
-       ;;
+    status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+    ;;
   #reload|force-reload)
-  #
   # If do_reload() is not implemented then leave this commented out
   # and leave 'force-reload' as an alias for 'restart'.
   #
-  #log_daemon_msg "Reloading $DESC" "$NAME"
-  #do_reload
-  #log_end_msg $?
-  #;;
+  #  log_daemon_msg "Reloading $DESC" "$NAME"
+  #  do_reload
+  #  log_end_msg $?
+  #  ;;
   restart|force-reload)
-  #
-  # If the "reload" option is implemented then remove the
-  # 'force-reload' alias
-  #
-  log_daemon_msg "Restarting $DESC" "$NAME"
-  do_stop
-  case "$?" in
-    0|1)
-    do_start
+    # If the "reload" option is implemented then remove the
+    # 'force-reload' alias
+    log_daemon_msg "Restarting $DESC" "$NAME"
+    do_stop
     case "$?" in
-      0) log_end_msg 0 ;;
-      1) log_end_msg 1 ;; # Old process is still running
-      *) log_end_msg 1 ;; # Failed to start
+      0|1)
+      do_start
+      case "$?" in
+        0) log_end_msg 0 ;;
+        1) log_end_msg 1 ;; # Old process is still running
+        *) log_end_msg 1 ;; # Failed to start
+      esac
+      ;;
+      *)
+      # Failed to stop
+      log_end_msg 1
+      ;;
     esac
     ;;
-    *)
-    # Failed to stop
-    log_end_msg 1
-    ;;
-  esac
-  ;;
   *)
-  #echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-  echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
-  exit 3
-  ;;
+    echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+    exit 3
+    ;;
 esac
 
 :
